### ISSUE TITLE
Parameter to provide backend in KeyV

### ISSUE THREAD

**Issue by piyushchauhan2011** [Kikobeats/cacheable-response#12]
I was wondering since, the underlying caching mechanism usage `keyv` and KeyV has support for the different backend for caching, can we provide some parameter to control that from cacheable-response ?

`cache = new Keyv({ namespace: 'ssr' }),`
 
  can be modified to have support for backend 

`new Keyv('redis://user:pass@localhost:6379', { namespace: 'cache' });`

**Comment by Kikobeats** [comment]
Just pass your custom `cache` instance:

```
{
  cache: new Keyv('redis://user:pass@localhost:6379', { namespace: 'cache' });
}
```

The [default](https://github.com/Kikobeats/cacheable-response/blob/master/index.js#L45) declaration is more a fallback to be used on dev mode.
