### ISSUE TITLE
Yarn workspaces  - EventSource's response has a MIME type ("text/html") that is not "text/event-stream"

### ISSUE THREAD

**Issue by ByronGBP** [Kikobeats/cacheable-response#13]
I've a project with a yarn workspaces architecture, following this [example](https://github.com/zeit/next.js/tree/canary/examples/with-yarn-workspaces) form the next.js documentation, that looks like:

packages
  |- webapp
  | |- pages
  | |- ...
  | |- server.js
  |- libraryA
  |- libraryB

server.js looks like
```
const cacheableResponse = require('cacheable-response');

const ssrCache = cacheableResponse({
  get: async ({ req, res, pagePath, queryParams }) => ({
    data: await app.renderToHTML(req, res, pagePath, queryParams),
    ttl: 7200000 // 2 hours
  }),
  send: ({ data, res }) => res.send(data)
});

app.prepare()
  .then(() => {
    const server = express();

    server.use('/_next', express.static(path.join(__dirname, '.next')));
    server.use('/static', express.static(path.join(__dirname, 'static')));
    
    .... 

    server.get('/account', (req, res) => {
        return ssrCache({ req, res, pagePath: '/account' });
    });

    ...
  }
);
```

And I'm getting this errors on the client

```
EventSource's response has a MIME type ("text/html") that is not "text/event-stream". Aborting the connection.
```
```
 Error with on-demand-entries-ping: Unexpected token < in JSON at position 0
```
 Which makes the website eventually fail until I make several hard refreshes. 

Do you have any idea why? 
Or maybe do you have a working example with yarn workspaces?

Also I had to specify `server.use('/_next', express.static(path.join(__dirname, '.next')));` and `server.use('/static', express.static(path.join(__dirname, 'static')));` because it didn't work without it.

Thanks 🙂

**Comment by Kikobeats** [comment]
No idea about yarn.

Did you try just the nextjs example, without your extra specific things?
