### ISSUE TITLE
Expose how cache key is computed

### ISSUE THREAD

**Issue by kodermax** [Kikobeats/cacheable-response#22]
Like this https://github.com/kodermax/cacheable-response/commit/21af4bd7af4d41d288298ca5bd87d6e652ed938a

**Comment by Kikobeats** [comment]
Hum, that doesn't mean mobile is not supported right now 🙂

In your fork, you need to check `CloudFront-Is-Mobile-Viewer` and that could be different in every use case.

For example, if you have a totally independent mobile site (like `m.site.com`) it means the site is totally different from the non-mobile, so it's supported by default.

Another example: Just using a query parameter for differentiating it in the cache storage should be enough (like `mobile=iphone`).

But I'm happy to support extend the default behavior, the most obvious next step could be possible to override `.getKey`, then you can put your custom logic here.

Thoughts?

**Comment by fabienheureux** [comment]
@Kikobeats  this could be a great idea/solution. I ended up to stop using cacheable-response because of lack of this feature (and lack of time to find a workaround).
