### ISSUE TITLE
Getting errors while using it with fastify-nextjs

### ISSUE THREAD

**Issue by jibin2706** [Kikobeats/cacheable-response#27]
**server.js**
```js
const cacheableResponse = require("cacheable-response");
const next = require("next");
const fastify = require("fastify");

const port = parseInt(process.env.PORT, 10) || 3000;
const dev = process.env.NODE_ENV !== "production";
const app = next({ dev });

const handle = app.getRequestHandler();

const ssrCache = cacheableResponse({
  ttl: 1000 * 60 * 60, // 1hour
  get: async ({ req, res, pagePath, queryParams }) => ({
    data: await app.renderToHTML(req, res, pagePath, queryParams)
  }),
  send: ({ data, res }) => res.send(data)
});

app.prepare().then(() => {
  const server = fastify({ logger: { level: "error" } });

  server.get("/", (req, res) => ssrCache({ req, res, pagePath: "/" }));

  server.get("/blog/:id", (req, res) => {
    const queryParams = { id: req.params.id };
    const pagePath = "/blog";
    return ssrCache({ req, res, pagePath, queryParams });
  });

  server.get("*", (req, res) => handle(req, res));

  server.listen(port, err => {
    if (err) throw err;
    console.log(`> Ready on http://localhost:${port}`);
  });
});
```

**Error Log**
```json
{"level":50,"time":1566390512702,"pid":31997,"hostname":"tss-H110M-H","reqId":1,"req":{"method":"GET","url":"/blog/first","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":60968},"res":{"statusCode":500},"err":{"type":"NodeError","message":"The \"url\" argument must be of type string. Received type undefined","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The \"url\" argument must be of type string. Received type undefined\n    at Url.parse (url.js:154:11)\n    at urlParse (url.js:148:13)\n    at Url.resolve (url.js:663:29)\n    at urlResolve (url.js:659:40)\n    at _getKey (/home/tss/ssr-caching-app/node_modules/cacheable-response/index.js:24:15)\n    at /home/tss/ssr-caching-app/node_modules/cacheable-response/index.js:87:17\n    at Object.server.get (/home/tss/ssr-caching-app/server.js:28:12)\n    at preHandlerCallback (/home/tss/ssr-caching-app/node_modules/fastify/lib/handleRequest.js:112:30)\n    at preValidationCallback (/home/tss/ssr-caching-app/node_modules/fastify/lib/handleRequest.js:101:5)\n    at handler (/home/tss/ssr-caching-app/node_modules/fastify/lib/handleRequest.js:70:5)"},"msg":"The \"url\" argument must be of type string. Received type undefined","v":1}
```

**Comment by Kikobeats** [comment]
> The "url" argument must be of type string. Received type undefined

Looks like at some point the url is not being passed as expected.

**Comment by jibin2706** [comment]
> Closing because it's a `cacheable-response` bug.
> 
> > The "url" argument must be of type string. Received type undefined
> 
> Looks like at some in your code point the url is not being passed as expected 🤔 .
> 
> Can you try to add some traces?
{"level":50,"time":1566713431011,"pid":13196,"hostname":"DESKTOP-B1VH7H0","reqId":1,"req":{"method":"GET","url":"/","hostname":"localhost:3000","remoteAddress":"127.0.0.1","remotePort":58397},"res":{"statusCode":500},"err":{"type":"NodeError","message":"The \"url\" argument must 
be of type string. Received type undefined","stack":"TypeError [ERR_INVALID_ARG_TYPE]: The \"url\" argument must be of type string. Received type undefined\n    at Url.parse (url.js:154:11)\n    at urlParse (url.js:148:13)\n    at Url.resolve (url.js:663:29)\n    at urlResolve (url.js:659:40)\n    at _getKey (C:\\Users\\jibin\\dev\\ssr-caching-app\\node_modules\\cacheable-response\\index.js:24:15)\n    at C:\\Users\\jibin\\dev\\ssr-caching-app\\node_modules\\cacheable-response\\index.js:87:17\n    at Object.server.get (C:\\Users\\jibin\\dev\\ssr-caching-app\\server.js:22:33)\n    at preHandlerCallback (C:\\Users\\jibin\\dev\\ssr-caching-app\\node_modules\\fastify\\lib\\handleRequest.js:112:30)\n    at preValidationCallback (C:\\Users\\jibin\\dev\\ssr-caching-app\\node_modules\\fastify\\lib\\handleRequest.js:101:5)\n    at handler (C:\\Users\\jibin\\dev\\ssr-caching-app\\node_modules\\fastify\\lib\\handleRequest.js:70:5)"},"msg":"The \"url\" argument must be of type 
string. Received type undefined","v":1}
url.js:154
    throw new ERR_INVALID_ARG_TYPE('url', 'string', url);
    ^

TypeError [ERR_INVALID_ARG_TYPE]: The "url" argument must be of type string. Received type undefined
    at Url.parse (url.js:154:11)
    at Object.urlParse [as parse] (url.js:148:13)
    at Server.handleRequest (C:\Users\jibin\dev\ssr-caching-app\node_modules\next-server\dist\server\next-server.js:87:31)
    at Object.server.get (C:\Users\jibin\dev\ssr-caching-app\server.js:30:33)
    at preHandlerCallback (C:\Users\jibin\dev\ssr-caching-app\node_modules\fastify\lib\handleRequest.js:112:30)
    at preValidationCallback (C:\Users\jibin\dev\ssr-caching-app\node_modules\fastify\lib\handleRequest.js:101:5)
    at handler (C:\Users\jibin\dev\ssr-caching-app\node_modules\fastify\lib\handleRequest.js:70:5)
    at handleRequest (C:\Users\jibin\dev\ssr-caching-app\node_modules\fastify\lib\handleRequest.js:19:5)
    at onRunMiddlewares (C:\Users\jibin\dev\ssr-caching-app\node_modules\fastify\lib\middleware.js:22:5)
    at middlewareCallback (C:\Users\jibin\dev\ssr-caching-app\node_modules\fastify\lib\route.js:358:5)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! ssr-caching@1.0.0 start: `NODE_ENV=production node server.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the ssr-caching@1.0.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\jibin\AppData\Roaming\npm-cache\_logs\2019-08-25T06_10_31_212Z-debug.log

Will this help?
