### ISSUE TITLE
Type Description for Typescript

### ISSUE THREAD

**Issue by rickynyairo** [Kikobeats/cacheable-response#29]
## Problem

I was trying to use the library on a typescript project and ended up having to silence or solve several linting errors since the type description for the library is not available. 

## Solution

I wrote a sample type description file [on this GitHub Gist](https://gist.github.com/rickynyairo/298957fa366b1ea510ba1042b754d84d)

## Action(s)

- If it already exists, please point me to a type description that I can use
- Please review the file and suggest any changes. 
- Upon approval, proceed with adding the description to [DefinitelyTyped](https://definitelytyped.org/) for access by future users.

Thank you. 
@Kikobeats

**Comment by Kikobeats** [comment]
I'm not using TypeScript, but yea I'll accept a PR over this 🙂
