### ISSUE TITLE
ETag is not implemented properly

### ISSUE THREAD

**Issue by sarneeh** [Kikobeats/cacheable-response#31]
I think that this library has some wrong assumptions on the `ETag` header. As I see the code, the `ETag` is being set on the response, but it's never read afterwards (on the request).

The library should look at the `If-None-Match` header and compare it to the cached response `ETag` and return `304 Not Modified` when they're the same. Now, the library always sends data after the response expired which is a waste.

![Example](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/images/http-cache-control.png)

**Comment by Kikobeats** [comment]
You're right, without `If-None-Match` validation then the process is not complete.

My concern right now is, is it worth to?

Why not remove it and just use `cache-control`?

**Comment by sarneeh** [comment]
@Kikobeats By just using `Cache-Control`, your server will always send data on the next request after cache expiry. By implementing `ETag` + `If-None-Match`, the server will not send any data, just return `304`, and the browser will understand that the cache is still valid. This is an improvement i.e. for mobile devices, which should save as much data on the network as possible.

If you don't mind I'd like to propose a PR with this 😄

**Comment by Kikobeats** [comment]
I'll be a pleasure to accept a PR about this 🙏
