### ISSUE TITLE
Breaking change in 1.10

### ISSUE THREAD

**Issue by kachkaev** [Kikobeats/cacheable-response#35]
I just upgraded deps and ended up with an unexpected error, caused by https://github.com/Kikobeats/cacheable-response/commit/a69239276d06d5fd1bcea204989bc1bfa26e09b9

This change of signature for `getKey` is breaking:

```diff
-(req, res) => ...
+({ req, res }) => ...
```

Took me quite some time to figure it out. I was using `req.headers.host` inside `getKey`, which now became `opts.headers.host` (`opts.headers` is undefined, hence `TypeError`).

Not sure what to do. Perhaps, the signature change should be reverted in `1.10.1`, followed by the release of the new signature as `2.0.0`

**Comment by Kikobeats** [comment]
Sorry for that; I added the migration guide as part of the release note
https://github.com/Kikobeats/cacheable-response/releases/tag/v1.10.0

🙂

**Comment by kachkaev** [comment]
🤔 Not sure if adding migration instructions will be enough for the users, because the [semver](https://semver.org/) 'contract' is still not followed. When upgrading from `x.y.0` to `x.z.0`, no migration steps are expected.

This is why `package.json` usually contains `"some-package": "^x.y.0"` (this means that `x.z.0` is good to go too). The only 'regression' that's allowed within one major version is now warnings, suggesting to refactor things in preparation to the next major version bump.

**Comment by Kikobeats** [comment]
I agree but based on npm, only two packages is using it https://www.npmjs.com/package/cacheable-response so it's not a big deal for this time

**Comment by stigkj** [comment]
I think that quite a lot of the usage of this library (which is very good, by the way :-) are directly from applications and not other libraries. So the numbers on `npmjs.com` does not really tell the whole truth :-)
