### ISSUE TITLE
?force=true to clear a cache

### ISSUE THREAD

**Issue by rodolphonetto** [Kikobeats/cacheable-response#36]
Hi, I use cacheable-response and it is very nice! thank you for the amazing job!

After all I don't think it is a issue... its more a question...

If I use my URL and ?force=true the next access will gerenate a new cache?

I mean, I have a news website and if I find a mistake I dont want to wait 10 minutes to people receive the new version of the site, will ?force=true clear the cache?

**Comment by Kikobeats** [comment]
Hello, as documentation is saying:

> In case you need you can force invalidate a cache response passing `force=true` as part of your query parameters.

so yes, it's forcing to regenerate the cache state 🙂

I don't know your use case, but a thing you can do is to ping the URL passing `url=true´ after deployment is done

Does make sense for you?
