### ISSUE TITLE
404s get cached and provided as 200

### ISSUE THREAD

**Issue by iankleist** [Kikobeats/cacheable-response#40]
Hi!

I followed the next.js ssr-caching example, so I've got a route like this: 

`server.get('/product/:handle', (req, res) => {
    const queryParams = { handle: req.params.handle };
    const pagePath = '/product/' + req.params.handle';
    return ssrCache({ req, res, pagePath, queryParams });
  });`

When a non-existent handle gets hit, the server responds with 404 but the second time it's 200. How can I prevent this?

**Comment by Kikobeats** [comment]
Hello,

I'm not using the Next.js, so I guess you need to open an issue or request for advice at Next.js repository 🙂

**Comment by iankleist** [comment]
Hi! Thanks for your fast reply! So this is a Next.js problem? It appears that cachable-response caches  requests with a 404 status code in my dynamic routes and provides them with a 200 status code.

**Comment by Kikobeats** [comment]
that's a thing depend on your code logic; If you call  `get` all the time, a new fresh cache copy will create independently of the http status code:

https://github.com/Kikobeats/cacheable-response#get

otherwise, if you want to prevent cache 404 status code, then don't call `get` under those scenarios. makes sense?

**Comment by iankleist** [comment]
Yes thanks, I tried to do that. Somehow I can't find a way to catch the 404's and prevent calling `get` before that. I'll figure it out eventually.

**Comment by Kikobeats** [comment]
In the current implementation, you can avoid store a value into the cache if you return `undefined` or `null`

https://github.com/Kikobeats/cacheable-response/blob/master/index.js#L85

so, if in your code workflow you return one of these values under your 404 error, then it should be enough to don't store it into the cache.

Can you confirm me that workflow works?

**Comment by iankleist** [comment]
Thank you @Kikobeats ... that works!

**Comment by Kikobeats** [comment]
@iankleist Thanks for confirming!

I'm going to extend docs to clarify about that 🙂

**Comment by Kikobeats** [comment]
done at https://github.com/Kikobeats/cacheable-response/commit/649de67300be5fe61b8562e4cd9f7b3c77a521be ✨

**Comment by lamb-mei** [comment]
@iankleist 
> 謝謝@Kikobeats ...有效！

How do you do it
I also use nextJS
In my Case
SSR get Data Error in .getInitalproos , it will cache error page
how to pass this case

@Kikobeats  any method focue remove cache

**Comment by iankleist** [comment]
@lamb-mei See this comment [here](https://github.com/zeit/next.js/issues/10551#issuecomment-587514523). Next.js will update their ssr-caching example to include the if-statement in said comment.

**Comment by lamb-mei** [comment]
Thank you @iankleist
