### ISSUE TITLE
iltorb has been deprecated

### ISSUE THREAD

**Issue by achmadk** [Kikobeats/cacheable-response#47]
according to [iltorb's author](https://www.npmjs.com/package/iltorb):
```
The zlib module provides APIs for brotli compression/decompression starting with Node.js v10.16.0, please use it over iltorb
```

how to use zlib to initialize cacheable-response with option `cache` is `true`?

**Comment by Kikobeats** [comment]
this package is using [compress-brotli](https://github.com/Kikobeats/compress-brotli) that can detect in a smart way Node.js iltorb or backup into npm package
