### ISSUE TITLE
Memory leak with keyv

### ISSUE THREAD

**Issue by soundstep** [Kikobeats/cacheable-response#49]
This is just a quick FYI.

I have a memory leak in production only with a SSR React app, related to the `keyv` module, which is used by `cacheable-response`.

Production urls are called with a lot of different query params:

```
example.com?campaign=1
example.com?campaign=2
example.com?campaign=3
example.com?campaign=4
```

This creates entries with a TTL, but these keys never get deleted due to a double prefix when the `delete` method is called, so the store keeps growing with pretty heavy values (full html response).

I created a PR to fix that: https://github.com/lukechilds/keyv/issues/108

I currently fixed the issue by keeping cacheable-response but setting the store to a Redis one.

I would argue that `keyv` strategy to delete keys set with a TTL is still pretty naive (not to say wrong), as the deletion will only happen the next time a `get` happens with the exact same key.

In my case, the same url may not be called twice, so even with the fix I made, the store would keep growing.

I strongly advise people with the same issue to move to Redis, as it has a proper TTL entry implemented:
https://redis.io/commands/expire

This was hard for us to find, that's why I said I had the bug in "production only" as we were not replaying traffic on test environments.

We may implement a way to create soak tests on our test environments to avoid these kind of issues, we are looking at https://github.com/buger/goreplay.

**Comment by Kikobeats** [comment]
Hey @soundstep thanks for this, I'm keyv maintainer so let's move ahead to fix the bug ASAP 🙂

**Comment by Kikobeats** [comment]
`keyv@4.0.1` was released for addressing this issue, thanks for reporting @soundstep 🙂
