### ISSUE TITLE
type mismatch in index.d.ts

### ISSUE THREAD

**Issue by WanChengCheng** [Kikobeats/cacheable-response#50]
* getKey is optional , but defined as required
* send is defined as (SendParams, ...any[]) but are called with send({ data, res, ...props })

**Comment by Kikobeats** [comment]
Can you make a PR?

**Comment by WanChengCheng** [comment]
> Can you make a PR?

sure, I've created a pr for you to review
https://github.com/Kikobeats/cacheable-response/pull/51
