### ISSUE TITLE
Is there a way to view cached data

### ISSUE THREAD

**Issue by rakeshkesavan** [Kikobeats/cacheable-response#56]
I'm using next.js and are trying to cache SSR. I'm trying to follow the simple solution described here: https://www.christopherkaiser.de/ssr-request-cache-for-react-next/

Is there a way to view the cached data either by consoling it or by browsing through a directory.

**Comment by Kikobeats** [comment]
Hey,

It depends where are you storing the data. See https://github.com/Kikobeats/cacheable-response#cache

If you use a regular database connector, then you can see the data with any GUI client 🙂
