### ISSUE TITLE
Getting 

### ISSUE THREAD

**Issue by ericlau-solid** [Kikobeats/cacheable-response#59]
Getting this error when using cacheable-response with nextjs server:

```
web-error.logErrorError [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:518:11)
    at /opt/prd/web/releases/33428632e3a0c8b1fbbfab3aa86d7e955654f639/packages/web/node_modules/cacheable-response/index.js:38:9
    at /opt/prd/web/releases/33428632e3a0c8b1fbbfab3aa86d7e955654f639/packages/web/node_modules/cacheable-response/index.js:104:5
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

Any attempt to catch / log at cacheable-response setup yields no console logs. It may be a nextjs issue but I can't tell from the stack trace.

**Comment by Kikobeats** [comment]
literally I can't do anything with this error report, also the title is not helping

**Comment by ericlau-solid** [comment]
Sorry for the sloppy title. Fixed. Also, this can stay closed as it turns out to be a nextjs issue. Apologies.

**Comment by Kikobeats** [comment]
No problem! I'll happy to add a note at README if special Next.js consideration should be taken 🙂
