### ISSUE TITLE
Purge cache custom page or custom url ?

### ISSUE THREAD

**Issue by emredusmez** [Kikobeats/cacheable-response#65]
I'm publishing real time user data. Whenever the user makes a change in their data, I will send a request to the next.js server and ask the current user to reset their cached page. example: cached url: https://example.com?user=exampleuser  .   User changed self data and   i want purge only https://example.com?user=exampleuser

**Comment by Kikobeats** [comment]
If you read the repo documentation, you can see that you can invalidate data passing `force=true` query parameter

so, try `https://example.com?user=exampleuser&force=true`

**Comment by emredusmez** [comment]
It works, but when I run force = true 1 time, I want the / exampleuser page to be updated as well. / extampleuser? force = true works fine but / exampleuser continues to fetch from cache
