### ISSUE TITLE
error importing cacheable-response

### ISSUE THREAD

**Issue by muhammedhaque** [Kikobeats/cacheable-response#69]
Hi there,

I am facing this issue when trying to use this library:

ERROR in ./node_modules/iltorb/build/bindings/iltorb.node 1:0
Module parse failed: Unexpected character '�' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
(Source code omitted for this binary file)
 @ ./node_modules/iltorb/index.js 10:39-78
 @ ./node_modules/compress-brotli/index.js
 @ ./node_modules/cacheable-response/index.js

(it also seems iltorb is now depreciated  - and recommends using zlib
Not sure if they are related.)

Any help appreciated !

**Comment by muhammedhaque** [comment]
it seems it is not being used in compress-brotli - can it be removed ?

**Comment by Kikobeats** [comment]
not sure why you are using webpack with this dependency since this is a backend-side thing 🤔 

what's your `cacheable-response` version?

**Comment by muhammedhaque** [comment]
thx for your reply.

We are using angular universal.
For the server backend :

/**
 * *** NOTE ON IMPORTING FROM ANGULAR AND NGUNIVERSAL IN THIS FILE ***
 *
 * If your application uses third-party dependencies, you'll need to
 * either use Webpack or the Angular CLI's `bundleDependencies` feature
 * in order to adequately package them for use on the server without a
 * node_modules directory.
 *
 * However, due to the nature of the CLI's `bundleDependencies`, importing
 * Angular in this file will create a different instance of Angular than
 * the version in the compiled application code. This leads to unavoidable
 * conflicts. Therefore, please do not explicitly import from @angular or
 * @nguniversal in this file. You can export any needed resources
 * from your application's main.server.ts file, as seen below with the
 * import for `ngExpressEngine`.
 */

Do we need it in compress-brotli if it is depreciated ?

**Comment by Kikobeats** [comment]
yes cause `compress-brotli` is not deprecated
