### ISSUE TITLE
aws lambda and cloudflare cdn

### ISSUE THREAD

**Issue by madruga8** [Kikobeats/cacheable-response#71]
Hello,

this package seems to be great, but before use it i would like to know if i can use with aws lambda due to serverless funcions limitations...

and also how can use it along with cloudflare cache-everything setup.

thank you very much.

**Comment by Kikobeats** [comment]
Hello, I'm not running things under AWS Lambda these days, but it should work like any HTTP Node.js server

Closing the issue but please feel free to comment 🙂
