### ISSUE TITLE
NextJs Caching Issue

### ISSUE THREAD

**Issue by gokulmhegde** [Kikobeats/cacheable-response#74]
https://github.com/vercel/next.js/tree/canary/examples/ssr-caching

Seems not to work on the current Next JS Version

Getting this error on Home Page

(node:20872) UnhandledPromiseRejectionWarning: TypeError: argument entity is required
    at etag (C:\xampp\htdocs\next-app\node_modules\etag\index.js:72:11)
    at C:\xampp\htdocs\next-app\node_modules\cacheable-response\index.js:93:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:20872) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:20872) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by Kikobeats** [comment]
Sorry for that, but I can't help since I'm not using Next.js on my use case and also never was the library intention.

BTW, take a look at https://github.com/vercel/next.js/tree/canary/examples/ssr-caching

**Comment by gokulmhegde** [comment]
The link which you have shared is the same.
which is not working.

**Comment by Kikobeats** [comment]
ops, https://github.com/rjyo/next-boost is the link I wanted to share 🙂
