### ISSUE TITLE
Cachable response setting headers

### ISSUE THREAD

**Issue by gokulmhegde** [Kikobeats/cacheable-response#75]
hi,
I was able to resolve my previous issue by my own.

Now i am having difficult time in setting headers

Please see my **server.js** File

const cacheableResponse = require("cacheable-response");
const express = require("express");
const next = require("next");

const port = parseInt(process.env.PORT, 10) || 5000;
const dev = process.env.NODE_ENV !== "production";
const app = next({ dev });

const handle = app.getRequestHandler();

const ssrCache = cacheableResponse({
  get: async ({ req, res, path }) => ({
    data: await new Promise((resolve) => {
      let data = app.render(req, res, path, {
        ...req.query,
        ...req.params,
      });
      return data
    }),
    ttl: 7200000, // 2 hours
  }),
  send: ({ data, res, req }) => res.send(data),
});

app.prepare().then(() => {
  const server = express();

  server.get("/post/:id", (req, res) => ssrCache({ req, res, path: "/post" }));

  server.get("/", (req, res) => ssrCache({ req, res, path: '/index' }));

  server.get("*", (req, res) => handle(req, res));

  server.listen(port, (err) => {
    if (err) throw err;
    console.log(`> Ready on http://localhost:${port}`);
  });
});

But in this headers are not setting which are show in 

node_modules\cacheable-response\index.js

Can you please help me, letting me know where i am doing wrong ?

**Comment by Kikobeats** [comment]
I can't read nothing there, please format the code first!

**Comment by gokulmhegde** [comment]
Hi,

Please check

const cacheableResponse = require("cacheable-response");
const express = require("express");
const next = require("next");

const port = parseInt(process.env.PORT, 10) || 5000;
const dev = process.env.NODE_ENV !== "production";
const app = next({
	dev
});

const handle = app.getRequestHandler();

const ssrCache = cacheableResponse({
	get: async({
		req,
		res,
		path
	}) => ({
		data: await new Promise((resolve) => {
			let data = app.render(req, res, path, {
				...req.query,
				...req.params,
			});
			return data
		}),
		ttl: 7200000, // 2 hours
	}),
	send: ({
		data,
		res,
		req
	}) => res.send(data),
});

app.prepare().then(() => {
			const server = express();

			server.get("/post/:id", (req, res) => ssrCache({
				req,
				res,
				path: "/post"
			}));

			server.get("/", (req, res) => ssrCache({
				req,
				res,
				path: '/index'
			}));

			server.get("*", (req, res) => handle(req, res));

			server.listen(port, (err) => {
					if (err) throw err;
					console.log( > Ready on http: //localhost:${port});
					});
			});

**Comment by Kikobeats** [comment]
The `data` function should be called every time a new request is performed.

So I guess the code there should be something like:

```js
data: async () => {
      const data = await app.render(req, res, path, {
				...req.query,
				...req.params,
			});

      return data
    }
```

can you try?

**Comment by Kikobeats** [comment]
Can you explain better what's the issue you are experimenting with?

Ideally, you don't need to set up any caching header there, `cacheble-response` does the job for you.

If `cacheable-response` is not doing the thing as expected that's probably you are not following the interface.

The `.get` method receives a function that returns a Promise:

https://github.com/Kikobeats/cacheable-response/blob/master/index.js#L81

I think your function there should to be similar to:

```
const get = async ({ req, res, path }) => {
  const data = await app.render(req, res, path, { ...req.query, ...req.params, })
  return { data, ttl: 7200000 }
}
```

Can you try it?

**Comment by gokulmhegde** [comment]
this is my changed server.js according to your suggestion
```
const cacheableResponse = require("cacheable-response");
const express = require("express");
const next = require("next");

const port = parseInt(process.env.PORT, 10) || 3000;
const dev = process.env.NODE_ENV !== "production";
const app = next({
  dev,
});

const handle = app.getRequestHandler();

const ssrCache = cacheableResponse({
  get: async ({ req, res, path }) => {
    const data = await app.render(req, res, path, {
      ...req.query,
      ...req.params,
    });
    return { data, ttl: 7200000 };
  },
  send: ({ data, res, req }) => res.send(data),
});

app.prepare().then(() => {
  const server = express();

  server.get("/post/:id", (req, res) =>
    ssrCache({
      req,
      res,
      path: "/post",
    })
  );

  server.get("/", (req, res) =>
    ssrCache({
      req,
      res,
      path: "/index",
    })
  );

  server.get("*", (req, res) => handle(req, res));

  server.listen(port, (err) => {
    if (err) throw err;
    console.log(`> Ready on http: //localhost:${port}`);
  });
});
```
this is giving me the error

**(node:9344) UnhandledPromiseRejectionWarning: TypeError: argument entity is required
    at etag (C:\xampp\htdocs\next-app\node_modules\etag\index.js:72:11)
    at C:\xampp\htdocs\next-app\node_modules\cacheable-response\index.js:93:32
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:9344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:9344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
{ id: '8' } {}
(node:9344) UnhandledPromiseRejectionWarning: TypeError: argument entity is required
    at etag (C:\xampp\htdocs\next-app\node_modules\etag\index.js:72:11)
    at C:\xampp\htdocs\next-app\node_modules\cacheable-response\index.js:93:32
(node:9344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)**

**Comment by gokulmhegde** [comment]
> this is my changed server.js according to your suggestion
> 
> ```
> const cacheableResponse = require("cacheable-response");
> const express = require("express");
> const next = require("next");
> 
> const port = parseInt(process.env.PORT, 10) || 3000;
> const dev = process.env.NODE_ENV !== "production";
> const app = next({
>   dev,
> });
> 
> const handle = app.getRequestHandler();
> 
> const ssrCache = cacheableResponse({
>   get: async ({ req, res, path }) => {
>     const data = await app.render(req, res, path, {
>       ...req.query,
>       ...req.params,
>     });
>     return { data, ttl: 7200000 };
>   },
>   send: ({ data, res, req }) => res.send(data),
> });
> 
> app.prepare().then(() => {
>   const server = express();
> 
>   server.get("/post/:id", (req, res) =>
>     ssrCache({
>       req,
>       res,
>       path: "/post",
>     })
>   );
> 
>   server.get("/", (req, res) =>
>     ssrCache({
>       req,
>       res,
>       path: "/index",
>     })
>   );
> 
>   server.get("*", (req, res) => handle(req, res));
> 
>   server.listen(port, (err) => {
>     if (err) throw err;
>     console.log(`> Ready on http: //localhost:${port}`);
>   });
> });
> ```
> 
> this is giving me the error
> 
> **(node:9344) UnhandledPromiseRejectionWarning: TypeError: argument entity is required at etag (C:\xampp\htdocs\next-app\node_modules\etag\index.js:72:11) at C:\xampp\htdocs\next-app\node_modules\cacheable-response\index.js:93:32 at processTicksAndRejections (internal/process/task_queues.js:93:5) (Use `node --trace-warnings ...` to show where the warning was created) (node:9344) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1) (node:9344) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**

I am behind this from days....

found no solution at all.

**Comment by Kikobeats** [comment]
the error trace is pointing to:


https://github.com/Kikobeats/cacheable-response/blob/master/index.js#L93

try to log what's happening there

**Comment by gokulmhegde** [comment]
On this

https://github.com/Kikobeats/cacheable-response/blob/master/index.js#L93

**cachedEtag || getEtag(serialize(data))**

both **cachedEtag** and **data** is **undefined**

**Comment by Kikobeats** [comment]
If data is undefined there means your render function is returning nothing.

Is that a expected thing?

**Comment by gokulmhegde** [comment]
The render function does not return the data.
It displays the response on the page. Let me see the documentation.
There is one more function **renderHTML**
let me see

**Comment by Kikobeats** [comment]
closing since it's an issue in our side, but please feel free to comment 🙂

**Comment by gokulmhegde** [comment]
I just wanted to know what does **data** object needs
Promise or anything else?

**Comment by Kikobeats** [comment]
data should be something can be serialized into a non undefined value
