### ISSUE TITLE
sending a HEAD will cache an empty result

### ISSUE THREAD

**Issue by macrozone** [Kikobeats/cacheable-response#86]
"cacheable-response": "^2.7.3",

when you do a `curl -I` (or `curl --head`) cacheable response will cache the result (in case of a MISS or STALE) , which is usually empty (depending on the underlying webapp). Subsequent HITs will return an empty page therefore even if called with another method

Its therefore possible for a malicious user to do a kind of denial of service attack.

My suggestion would be to only allow GET requests to be cached and/or always incorperate the method into the cache-key

**Comment by Kikobeats** [comment]
cacheable-response doesn't handle any kind of HTTP router – that's a thing should be done from your side!

**Comment by macrozone** [comment]
@Kikobeats the problem only happens with the new `staleTtl` property. If i do a HEAD request in the stale grace period, cacheable response will cache an empty page.

this surprisingly does not happen with `?force` or when cache is EXPIRED.

I would not close that, this is a serious issue and a pitfall. I would also check your own apps whether you can DOS yourself.

**Comment by macrozone** [comment]
@Kikobeats ok i found out that the new version will no longer work properly with nextjs. Probably because the `req` will already be closed when it tries to revalidate in the background.

nextjs removed all examples that used cacheable-response.

So i just stay at `2.1.7` as this worked flawlessly

**Comment by Kikobeats** [comment]
Hum cacheable-response support revalidate on background:
https://github.com/Kikobeats/cacheable-response#stalettl

That is a thing recently added. Maybe a better Next.js integration could be done?

Appreciated if you can investigate that. I will happy to add some documentation over that on the README.
