### ISSUE TITLE
export default `getKey`/`createKey` function

### ISSUE THREAD

**Issue by macrozone** [Kikobeats/cacheable-response#88]
the default `getKey` function or more precisely the `createKey` function is not that trivial. 

In our case we want to prefix it with a build-id, so that after a deployement responses get a new cache key (and therefore MISS). 

This is often crucial because the cached response often also caches resources like js-bundles and css files. If the names of these bundles change (which is often the case), the cached response will point to the wrong js bundles that no longer exist on the server.

**Comment by Kikobeats** [comment]
correct me if I'm wrong but I think you can access to that function in this way:

```js
const { createKey } = require('cacheable-response/src/util')
```

**Comment by macrozone** [comment]
> correct me if I'm wrong but I think you can access to that function in this way:
> 
> ```js
> const { createKey } = require('cacheable-response/src/util')
> ```

not directly with typescript as it is missing proper definition

**Comment by Kikobeats** [comment]
oh sorry for that, I'm not a regular TypeScript user (that is why the type definition file was outdated).

Is it a way to add it as part of the definition? 🤔
