### ISSUE TITLE
no longer works with "@keyv/mongo"

### ISSUE THREAD

**Issue by macrozone** [Kikobeats/cacheable-response#89]
i did not debug it yet, but using "@keyv/mongo" i noticed that no entries were added to the database.

**Comment by Kikobeats** [comment]
Appreciated if you can investigate a bit more and create a proper issue at https://github.com/microlinkhq/keyv.

The interaction with any keyv storage is done via memorize
https://github.com/Kikobeats/cacheable-response/blob/master/src/index.js#L37

so not sure what's happening there. Closing for now but please feel free to reply
